# Generated by Django 2.2.3 on 2019-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='用户手机')),
                ('email', models.EmailField(max_length=50, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('isValid', models.BooleanField(default=False, verbose_name='禁用')),
            ],
            options={
                'verbose_name': 'user_info',
                'verbose_name_plural': 'user_info',
            },
        ),
    ]
