# Generated by Django 2.2.3 on 2019-07-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190728_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=20, verbose_name='博客标题')),
                ('content', models.TextField(verbose_name='博客正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isValid', models.BooleanField(default=False, verbose_name='禁用')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blog',
                'db_table': 'blog',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='更改时间'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('isValid', models.BooleanField(default=False, verbose_name='禁用')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='博客评论')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserInfo')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='博客类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('isValid', models.BooleanField(default=False, verbose_name='禁用')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='博客类型')),
            ],
            options={
                'verbose_name': 'classify',
                'verbose_name_plural': 'classify',
                'db_table': 'classify',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserInfo', verbose_name='博客作者'),
        ),
    ]
